apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret
type: Opaque
data:
  # Kibana usa as mesmas credenciais do Elasticsearch
  username: ZWxhc3RpYw==  # elastic
  password: c2VuaGEtc2VncmVkYQ==  # senha-segreda