apiVersion: v1
kind: Secret
metadata:
  name: redpanda-secret
  labels:
    app: redpanda
    component: messaging
type: Opaque
data:
  admin-user: YWRtaW4=  # admin
  admin-password: c2VuaGEtc2VncmVkYQ==  # senha-segreda
  superuser: cmVkcGFuZGE=  # redpanda
  superuser-password: c2VuaGEtc2VncmVkYQ==  # senha-segreda