apiVersion: v1
kind: Service
metadata:
  name: redpanda-client
  labels:
    app: redpanda
    component: messaging
spec:
  selector:
    app: redpanda
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  - name: admin
    port: 9644
    targetPort: 9644
  type: ClusterIP