apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: production-messaging
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:v24.2.1  # Use official image
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Create configuration
            cat > /etc/redpanda/redpanda.yaml << 'EOF'
            redpanda:
              data_directory: /var/lib/redpanda/data
              node_id: 0
              seed_servers: []
              rpc_server:
                address: 0.0.0.0
                port: 33145
              kafka_api:
                - address: 0.0.0.0
                  port: 9092
                  name: PLAINTEXT
              admin:
                - address: 0.0.0.0
                  port: 9644
              advertised_kafka_api:
                - address: 0.0.0.0  # Will be accessible via service
                  port: 9092
                  name: PLAINTEXT
              auto_create_topics_enabled: true
              developer_mode: true
            EOF
            
            # Start Redpanda
            exec rpk redpanda start \
              --config /etc/redpanda/redpanda.yaml \
              --smp 1 \
              --memory 2G \
              --overprovisioned \
              --check=false
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 33145
          name: rpc
        - containerPort: 9644
          name: admin
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1"
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        - name: config
          mountPath: /etc/redpanda/redpanda.yaml
          subPath: redpanda.yaml
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: redpanda-config
          items:
          - key: redpanda.yaml
            path: redpanda.yaml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
      storageClassName: local-path  # Add this!