apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest-fips
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Extract node ID from pod name
            NODE_ID=${HOSTNAME##*-}
            echo "Starting Redpanda with node_id=${NODE_ID}"
            
            # Export for envsubst
            export NODE_ID
            
            # Create final config from template
            cat /etc/redpanda/redpanda.yaml.template | envsubst > /etc/redpanda/redpanda.yaml
            
            # Debug: show the generated config
            echo "=== Generated Configuration ==="
            cat /etc/redpanda/redpanda.yaml
            echo "=== End Configuration ==="
            
            # Start Redpanda with all flags
            exec rpk redpanda start \
              --config /etc/redpanda/redpanda.yaml \
              --overprovisioned \
              --smp 1 \
              --memory 2G \
              --reserve-memory 1G \
              --node-id ${NODE_ID} \
              --check=false
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 33145
          name: rpc
        - containerPort: 9644
          name: admin
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        - name: config
          mountPath: /etc/redpanda/redpanda.yaml.template
          subPath: redpanda.yaml
          readOnly: true
        # Add startup probe to give Redpanda time to start
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9092'
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 10
        # Use exec probe instead of tcpSocket for better control
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check if Redpanda is responding on admin API
              curl -f http://localhost:9644/v1/status/ready || exit 1
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check Kafka API
              timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9092' && \
              # Check Admin API
              curl -f http://localhost:9644/v1/status/ready
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: config
        configMap:
          name: redpanda-config
          items:
          - key: redpanda.yaml
            path: redpanda.yaml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi