apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 2
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: vectorized/redpanda:latest
        args:
          - start
          - --overprovisioned
          - --smp 1
          - --memory 2G
          - --reserve-memory 1G
          - --kafka-addr PLAINTEXT://0.0.0.0:9092
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        - name: config
          mountPath: /etc/redpanda/redpanda.yaml
          subPath: redpanda.yaml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
  volumes:
    - name: config
      configMap:
        name: redpanda-config
