apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest-fips
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Mostrar configuração
            echo "=== Configuração ==="
            cat /etc/redpanda/redpanda.yaml
            
            # Usar rpk redpanda start (NÃO container start)
            echo "=== Iniciando Redpanda ==="
            exec rpk redpanda start \
              --config /etc/redpanda/redpanda.yaml \
              --overprovisioned \
              --check=false
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: REDPANDA_ENVIRONMENT
          value: "kubernetes"
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 33145
          name: rpc
        - containerPort: 9644
          name: admin
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1"
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        - name: config
          mountPath: /etc/redpanda/redpanda.yaml
          subPath: redpanda.yaml
          readOnly: true
        # Probes mais tolerantes
        startupProbe:
          tcpSocket:
            port: 9092
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Verifica se Redpanda responde no admin API
              curl -f http://localhost:9644/v1/status/ready >/dev/null 2>&1 || exit 1
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: redpanda-config
          items:
          - key: redpanda.yaml
            path: redpanda.yaml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi