apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest-fips
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Get node ID from pod name (removes "redpanda-" prefix)
            NODE_ID=${HOSTNAME##*-}
            echo "Starting Redpanda with node_id=${NODE_ID}"
            
            # Set environment variable for substitution
            export NODE_ID
            
            # Create config with substituted node_id
            cat /etc/redpanda/redpanda.yaml.template | envsubst > /etc/redpanda/redpanda.yaml
            
            # Start Redpanda
            exec rpk redpanda start \
              --config /etc/redpanda/redpanda.yaml \
              --overprovisioned \
              --smp 1 \
              --memory 2G \
              --reserve-memory 1G \
              --node-id ${NODE_ID}
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 33145
          name: rpc
        - containerPort: 9644
          name: admin
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        - name: config
          mountPath: /etc/redpanda/redpanda.yaml.template
          subPath: redpanda.yaml
          readOnly: true
        # Add a startup probe to ensure Redpanda is ready
        startupProbe:
          tcpSocket:
            port: 9092
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: config
        configMap:
          name: redpanda-config
          items:
          - key: redpanda.yaml
            path: redpanda.yaml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi