apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest-fips
        command: ["rpk"]
        args:
          - "redpanda"
          - "start"
          - "--smp"
          - "1"
          - "--memory"
          - "2G"
          - "--overprovisioned"
          - "--check=false"
          - "--kafka-addr"
          - "PLAINTEXT://0.0.0.0:9092"
          - "--advertise-kafka-addr"
          - "PLAINTEXT://$(POD_NAME).redpanda.production-messaging.svc.cluster.local:9092"
          - "--rpc-addr"
          - "0.0.0.0:33145"
          - "--advertise-rpc-addr"
          - "$(POD_NAME).redpanda.production-messaging.svc.cluster.local:33145"
          - "--admin"
          - "0.0.0.0:9644"
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 33145
          name: rpc
        - containerPort: 9644
          name: admin
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path