# statefulset-container.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest-fips
        command: ["rpk"]
        args:
          - "container"
          - "start"
          - "--mode"
          - "dev"
          - "--check=false"
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 33145
          name: rpc
        - containerPort: 9644
          name: admin
        # ... resto igual