apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest-fips
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Configuração com admin endpoint
            cat > /tmp/redpanda.yaml << 'EOF'
            node_id: 0
            data_directory: /var/lib/redpanda/data
            developer_mode: true
            # Configuração para admin/UI
            admin:
              - address: 0.0.0.0
                port: 9644
            EOF
            
            # Iniciar Redpanda com flags que forçam bind externo
            exec /opt/redpanda/bin/redpanda \
              --redpanda-cfg /tmp/redpanda.yaml \
              --smp=1 \
              --memory=2G \
              --overprovisioned \
              --check=false
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 33145
          name: rpc
        - containerPort: 9644
          name: admin
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        - name: config
          mountPath: /etc/redpanda/redpanda.yaml
          subPath: redpanda.yaml
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: redpanda-config
          items:
          - key: redpanda.yaml
            path: redpanda.yaml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
      storageClassName: local-path