apiVersion: v1
kind: Service
metadata:
  name: cassandra-client
  labels:
    app: cassandra
    component: nosql
spec:
  selector:
    app: cassandra
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
  type: ClusterIP