- hosts: all
  become: yes
  roles:
    - base

- hosts: debian
  roles:
    - role: k3s
    - role: argocd
      vars:
        k3s_version: "v1.27.10+k3s1"
        argocd_namespace: "argocd"
        argocd_server_nodeport: 30007
        ansible_user_home: "/home/{{ ansible_user | default('ubuntu') }}"
        k3s_manifest_dir: /var/lib/rancher/k3s/server/manifests
    - role: k9s

#- import_playbook: ansible/playbooks/bootstrap.yml