{
 "title": "1     Node Exporter for Prometheus Dashboard CN 20201010",
 "description": "ã€ä¸­æ–‡ç‰ˆæœ¬ã€‘2020.10.10æ›´æ–°ï¼Œå¢žåŠ æ•´ä½“èµ„æºå±•ç¤ºï¼æ”¯æŒ Grafana6&7ï¼ŒNode Exporter v0.16åŠä»¥ä¸Šçš„ç‰ˆæœ¬ï¼Œä¼˜åŒ–é‡è¦æŒ‡æ ‡å±•ç¤ºã€‚åŒ…å«æ•´ä½“èµ„æºå±•ç¤ºä¸Žèµ„æºæ˜Žç»†å›¾è¡¨ï¼šCPU å†…å­˜ ç£ç›˜ IO ç½‘ç»œç­‰ç›‘æŽ§æŒ‡æ ‡ã€‚https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "æ•°æ®æº",
    "query": "label_values(origin_prometheus)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
   },
   {
    "name": "hostname",
    "label": "ä¸»æœºå",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "ç½‘å¡",
    "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   { "name": "interval", "label": "æ—¶é—´é—´éš”", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "æœ€å¤§æŒ‚è½½ç›®å½•",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "å±•ç¤ºä½¿ç”¨çš„ä¸»æœºå",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   {
    "name": "total",
    "label": "ä¸»æœºæ•°",
    "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "èµ„æºæ€»è§ˆï¼ˆå…³è”JOBé¡¹ï¼‰å½“å‰é€‰ä¸­ä¸»æœºï¼š$show_hostnameï¼Œå®žä¾‹ï¼š$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "æœåŠ¡å™¨èµ„æºæ€»è§ˆè¡¨ã€JOBï¼š$jobï¼Œä¸»æœºæ€»æ•°ï¼š$totalã€‘",
   "type": "table-old",
   "description": "åˆ†åŒºä½¿ç”¨çŽ‡ã€ç£ç›˜è¯»å–ã€ç£ç›˜å†™å…¥ã€ä¸‹è½½å¸¦å®½ã€ä¸Šä¼ å¸¦å®½ï¼Œå¦‚æžœæœ‰å¤šä¸ªç½‘å¡æˆ–è€…å¤šä¸ªåˆ†åŒºï¼Œæ˜¯é‡‡é›†çš„ä½¿ç”¨çŽ‡æœ€é«˜çš„ç½‘å¡æˆ–è€…åˆ†åŒºçš„æ•°å€¼ã€‚\n\nè¿žæŽ¥æ•°ï¼šCurrEstab - å½“å‰çŠ¶æ€ä¸º ESTABLISHED æˆ– CLOSE-WAIT çš„ TCP è¿žæŽ¥æ•°ã€‚",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "ä¸»æœºå"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})by(instance)",
     "legendFormat": "è¿è¡Œæ—¶é—´"
    },
    {
     "expr": "node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "æ€»å†…å­˜"
    },
    {
     "expr": "count(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "æ€»æ ¸æ•°"
    },
    {
     "expr": "node_load5{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}",
     "legendFormat": "5åˆ†é’Ÿè´Ÿè½½"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPUä½¿ç”¨çŽ‡"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} / (node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})))* 100",
     "legendFormat": "å†…å­˜ä½¿ç”¨çŽ‡"
    },
    {
     "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "åˆ†åŒºä½¿ç”¨çŽ‡"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "æœ€å¤§è¯»å–"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "æœ€å¤§å†™å…¥"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "è¿žæŽ¥æ•°"
    },
    {
     "expr": "node_sockstat_TCP_tw{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "ä¸‹è½½å¸¦å®½"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "ä¸Šä¼ å¸¦å®½"
    }
   ]
  },
  {
   "title": "$jobï¼šæ•´ä½“æ€»è´Ÿè½½ä¸Žæ•´ä½“å¹³å‡CPUä½¿ç”¨çŽ‡",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "æ€»è´Ÿè½½" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", mode='system'})",
     "legendFormat": "æ€»æ ¸æ•°"
    },
    {
     "expr": "sum(node_load5{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})",
     "legendFormat": "æ€»5åˆ†é’Ÿè´Ÿè½½"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "æ€»å¹³å‡ä½¿ç”¨çŽ‡"
    }
   ]
  },
  {
   "title": "$jobï¼šæ•´ä½“æ€»å†…å­˜ä¸Žæ•´ä½“å¹³å‡å†…å­˜ä½¿ç”¨çŽ‡",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "æ€»å†…å­˜é‡" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})",
     "legendFormat": "æ€»å†…å­˜"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})",
     "legendFormat": "æ€»å·²ç”¨"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))*100",
     "legendFormat": "æ€»å¹³å‡ä½¿ç”¨çŽ‡"
    }
   ]
  },
  {
   "title": "$jobï¼šæ•´ä½“æ€»ç£ç›˜ä¸Žæ•´ä½“å¹³å‡ç£ç›˜ä½¿ç”¨çŽ‡",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "æ€»ç£ç›˜é‡" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "æ€»ç£ç›˜é‡"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "æ€»ä½¿ç”¨é‡"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "æ€»å¹³å‡ä½¿ç”¨çŽ‡"
    }
   ]
  },
  {
   "title": "èµ„æºæ˜Žç»†ï¼šã€$show_hostnameã€‘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "è¿è¡Œæ—¶é—´",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "æ€»CPUä½¿ç”¨çŽ‡"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "å†…å­˜ä½¿ç”¨çŽ‡"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "æœ€å¤§åˆ†åŒº({{mountpoint}})ä½¿ç”¨çŽ‡"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "äº¤æ¢åˆ†åŒºä½¿ç”¨çŽ‡"
    }
   ]
  },
  {
   "title": "ã€$show_hostnameã€‘ï¼šå„åˆ†åŒºå¯ç”¨ç©ºé—´(EXT.*/XFS)",
   "type": "table-old",
   "description": "æœ¬çœ‹æ¿ä¸­çš„ï¼šç£ç›˜æ€»é‡ã€ä½¿ç”¨é‡ã€å¯ç”¨é‡ã€ä½¿ç”¨çŽ‡ä¿æŒå’Œdfå‘½ä»¤çš„Sizeã€Usedã€Availã€Use% åˆ—çš„å€¼ä¸€è‡´ï¼Œå¹¶ä¸”Use%çš„å€¼ä¼šå››èˆäº”å…¥ä¿ç•™ä¸€ä½å°æ•°ï¼Œä¼šæ›´åŠ å‡†ç¡®ã€‚\n\næ³¨ï¼šdfä¸­Use%ç®—æ³•ä¸ºï¼š(size - free) * 100 / (avail + (size - free))ï¼Œç»“æžœæ˜¯æ•´é™¤åˆ™ä¸ºè¯¥å€¼ï¼Œéžæ•´é™¤åˆ™ä¸ºè¯¥å€¼+1ï¼Œç»“æžœçš„å•ä½æ˜¯%ã€‚\nå‚è€ƒdfå‘½ä»¤æºç ï¼š",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "æ€»é‡"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "æ¯å°æ—¶æµé‡$device",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "ä¸Šä¼ ï¼ˆ-ï¼‰/ä¸‹è½½ï¼ˆ+ï¼‰" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_inä¸‹è½½"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_outä¸Šä¼ "
    }
   ]
  },
  {
   "title": "CPU æ ¸æ•°",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": "å‰©ä½™èŠ‚ç‚¹æ•°:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "æ€»å†…å­˜",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "æ€»æ–‡ä»¶æè¿°ç¬¦",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPUä½¿ç”¨çŽ‡",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "ç³»ç»Ÿä½¿ç”¨çŽ‡"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "ç”¨æˆ·ä½¿ç”¨çŽ‡"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "ç£ç›˜IOä½¿ç”¨çŽ‡"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "æ€»ä½¿ç”¨çŽ‡"
    }
   ]
  },
  {
   "title": "å†…å­˜ä¿¡æ¯",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "æ€»å†…å­˜"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "å·²ç”¨"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "å¯ç”¨"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "ä½¿ç”¨çŽ‡"
    }
   ]
  },
  {
   "title": "æ¯ç§’ç½‘ç»œå¸¦å®½ä½¿ç”¨$device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "ä¸Šä¼ ï¼ˆ-ï¼‰/ä¸‹è½½ï¼ˆ+ï¼‰" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_inä¸‹è½½"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_outä¸Šä¼ "
    }
   ]
  },
  {
   "title": "ç³»ç»Ÿå¹³å‡è´Ÿè½½",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1åˆ†é’Ÿè´Ÿè½½"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5åˆ†é’Ÿè´Ÿè½½"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15åˆ†é’Ÿè´Ÿè½½"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPUæ€»æ ¸æ•°"
    }
   ]
  },
  {
   "title": "æ¯ç§’ç£ç›˜è¯»å†™å®¹é‡",
   "type": "graph",
   "description": "Read bytes æ¯ä¸ªç£ç›˜åˆ†åŒºæ¯ç§’è¯»å–çš„æ¯”ç‰¹æ•°\nWritten bytes æ¯ä¸ªç£ç›˜åˆ†åŒºæ¯ç§’å†™å…¥çš„æ¯”ç‰¹æ•°",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "Bps", "label": "è¯»å–ï¼ˆ-ï¼‰/å†™å…¥ï¼ˆ+ï¼‰" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_è¯»å–"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_å†™å…¥"
    }
   ]
  },
  {
   "title": "ç£ç›˜ä½¿ç”¨çŽ‡",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "ç£ç›˜è¯»å†™é€ŸçŽ‡ï¼ˆIOPSï¼‰",
   "type": "graph",
   "description": "Reads completed: æ¯ä¸ªç£ç›˜åˆ†åŒºæ¯ç§’è¯»å®Œæˆæ¬¡æ•°\n\nWrites completed: æ¯ä¸ªç£ç›˜åˆ†åŒºæ¯ç§’å†™å®Œæˆæ¬¡æ•°\n\nIO now æ¯ä¸ªç£ç›˜åˆ†åŒºæ¯ç§’æ­£åœ¨å¤„ç†çš„è¾“å…¥/è¾“å‡ºè¯·æ±‚æ•°",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    {
     "format": "iops",
     "label": "è¯»å–ï¼ˆ-ï¼‰/å†™å…¥ï¼ˆ+ï¼‰I/O ops/sec"
    }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_è¯»å–"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_å†™å…¥"
    }
   ]
  },
  {
   "title": "æ¯1ç§’å†…I/Oæ“ä½œè€—æ—¶å æ¯”",
   "type": "graph",
   "description": "æ¯ä¸€ç§’é’Ÿçš„è‡ªç„¶æ—¶é—´å†…ï¼ŒèŠ±è´¹åœ¨I/Oä¸Šçš„è€—æ—¶ã€‚ï¼ˆwall-clock timeï¼‰\n\nnode_disk_io_time_seconds_totalï¼š\nç£ç›˜èŠ±è´¹åœ¨è¾“å…¥/è¾“å‡ºæ“ä½œä¸Šçš„ç§’æ•°ã€‚è¯¥å€¼ä¸ºç´¯åŠ å€¼ã€‚ï¼ˆMilliseconds Spent Doing I/Osï¼‰\n\nrate(node_disk_io_time_seconds_total[1m])ï¼š\nè®¡ç®—æ¯ç§’çš„é€ŸçŽ‡ï¼š(lastå€¼-lastå‰ä¸€ä¸ªå€¼)/æ—¶é—´æˆ³å·®å€¼ï¼Œå³ï¼š1ç§’é’Ÿå†…ç£ç›˜èŠ±è´¹åœ¨I/Oæ“ä½œçš„æ—¶é—´å æ¯”ã€‚",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_æ¯ç§’I/Oæ“ä½œ%"
    }
   ]
  },
  {
   "title": "æ¯æ¬¡IOè¯»å†™çš„è€—æ—¶ï¼ˆå‚è€ƒï¼šå°äºŽ100msï¼‰(beta)",
   "type": "graph",
   "description": "Read time seconds æ¯ä¸ªç£ç›˜åˆ†åŒºè¯»æ“ä½œèŠ±è´¹çš„ç§’æ•°\n\nWrite time seconds æ¯ä¸ªç£ç›˜åˆ†åŒºå†™æ“ä½œèŠ±è´¹çš„ç§’æ•°\n\nIO time seconds æ¯ä¸ªç£ç›˜åˆ†åŒºè¾“å…¥/è¾“å‡ºæ“ä½œèŠ±è´¹çš„ç§’æ•°\n\nIO time weighted secondsæ¯ä¸ªç£ç›˜åˆ†åŒºè¾“å…¥/è¾“å‡ºæ“ä½œèŠ±è´¹çš„åŠ æƒç§’æ•°",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "s", "label": "è¯»å–ï¼ˆ-ï¼‰/å†™å…¥ï¼ˆ+ï¼‰" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_è¯»å–"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_å†™å…¥"
    }
   ]
  },
  {
   "title": "ç½‘ç»œSocketè¿žæŽ¥ä¿¡æ¯",
   "type": "graph",
   "description": "Sockets_used - å·²ä½¿ç”¨çš„æ‰€æœ‰åè®®å¥—æŽ¥å­—æ€»é‡\n\nCurrEstab - å½“å‰çŠ¶æ€ä¸º ESTABLISHED æˆ– CLOSE-WAIT çš„ TCP è¿žæŽ¥æ•°\n\nTCP_alloc - å·²åˆ†é…ï¼ˆå·²å»ºç«‹ã€å·²ç”³è¯·åˆ°sk_buffï¼‰çš„TCPå¥—æŽ¥å­—æ•°é‡\n\nTCP_tw - ç­‰å¾…å…³é—­çš„TCPè¿žæŽ¥æ•°\n\nUDP_inuse - æ­£åœ¨ä½¿ç”¨çš„ UDP å¥—æŽ¥å­—æ•°é‡\n\nRetransSegs - TCP é‡ä¼ æŠ¥æ–‡æ•°\n\nOutSegs - TCP å‘é€çš„æŠ¥æ–‡æ•°\n\nInSegs - TCP æŽ¥æ”¶çš„æŠ¥æ–‡æ•°",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "æ‰“å¼€çš„æ–‡ä»¶æè¿°ç¬¦(å·¦ )/æ¯ç§’ä¸Šä¸‹æ–‡åˆ‡æ¢æ¬¡æ•°(å³)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "ä½¿ç”¨çš„æ–‡ä»¶æè¿°ç¬¦" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "ä½¿ç”¨çš„æ–‡ä»¶æè¿°ç¬¦"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "æ¯ç§’ä¸Šä¸‹æ–‡åˆ‡æ¢æ¬¡æ•°"
    }
   ]
  }
 ]
}