apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-staging
spec:
  template:
    spec:
      containers:
        - name: php
          env:
            - name: APP_ENV
              value: staging
