apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
    component: nosql
type: Opaque
data:
  root-username: YWRtaW4=  # admin
  root-password: c2VuaGEtc2VnZ3JlZGE=  # senha-segreda
  database: YXBwZGIK  # appdb
  username: YXBwdXNlcg==  # appuser
  password: YXBwcGFzc3dvcmQ=  # apppassword