apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret
  labels:
    app: kibana
    component: search
type: Opaque
data:
  encryption-key: c29tZXRoaW5nX2F0X2xlYXN0XzMyX2NoYXJhY3RlcnM=  # something_at_least_32_characters
  reporting-encryption-key: c29tZXRoaW5nX2F0X2xlYXN0XzMyX2NoYXJhY3RlcnM=  # something_at_least_32_characters