apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  # em produção, Kafka pode ter autenticação SASL/SSL
  username: a2Fma2E=  # kafka
  password: c2VuaGEtc2VncmVkYQ==  # senha-segreda