apiVersion: v1
kind: Service
metadata:
  name: kafka-client
  labels:
    app: kafka
    component: messaging
spec:
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  type: ClusterIP