apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  labels:
    app: elasticsearch
    component: search
type: Opaque
data:
  password: c2VuaGEtc2VncmVkYQ==  # senha-segreda
  ca.crt: ""
  tls.crt: ""
  tls.key: ""