apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: rabbitmq
    component: messaging
type: Opaque
data:
  erlang-cookie: U1dLREZKU0xLREZKU0xLREZK  # base64 do cookie
  username: YWRtaW4=  # admin
  password: c2VuaGEtc2VncmVkYQ==  # senha-segreda