apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickvisual-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
          storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
