---
- name: Bootstrap + Kubernetes + GitOps
  hosts: all
  become: true
  gather_facts: true

  vars:
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml

  pre_tasks:
    - name: Check systemd is running
      command: systemctl is-system-running
      register: systemd_status
      failed_when: false
      changed_when: false

    - name: Show systemd status
      debug:
        msg: "Systemd status: {{ systemd_status.stdout }}"

  roles:
    - role: common
      tags: [common, base]

    - role: k3s
      tags: [k3s, kubernetes]

    - role: tools
      tags: [tools, cli]

    - role: argocd
      tags: [argocd, gitops]

  post_tasks:
    - name: Ensure kubeconfig permissions
      roles:
        group: root
        mode: '0644'
      when: ansible_facts['os_family'] == "Debian"

    - name: Show cluster info
      shell: kubectl cluster-info
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: cluster_info
      changed_when: false

    - name: Cluster info output
      debug:
        var: cluster_info.stdout
