apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    component: relational
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: c2VuaGEtc2VncmVkYQ==  # senha-segreda
  database: YXBwZGIK  # appdb