apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: main-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
